### ISSUE TITLE
Error terms for failed http_open/3 ?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [aarroyoc/scryer-playground#31]
The file system open/3 gives me an error term,
in case a file does not exist or cannot be accessed:
```
/* Scryer Prolog 0.9.4-165 */
?- open('abracadabra', read, X).
   error(existence_error(source_sink,"abracadabra"),open/4).
```
What about http_open/3, some error terms planned?
Currently http_open/3 is silent in Scryer Prolog:
```
/* Scryer Prolog 0.9.4-165*/
?- use_module(library(http/http_open)).
   true.

?- http_open("https://locahost/foo.html", S, []).
   false.

?- http_open("https://localhost:9999/foo.html", S, []).
   false.
```
This is unlike SWI-Prolog:
```
/* SWI-Prolog 9.3.8 */
?- use_module(library(http/http_open)).
   true.

?- http_open("https://locahost/foo.html", S, []).
ERROR: Socket error: Host not found

?- http_open("https://localhost:9999/foo.html", S, []).
ERROR: Socket error: Connection refused
```

**Comment by bakaq** [comment]
This is unrelated to the issue reported (which is a good one), but I've been wanting to ask this for quite a while: why do you report general issues with Scryer Prolog here (the Scryer Playground repo) instead of the [main Scryer Prolog repo](https://github.com/mthom/scryer-prolog) where they would make much more sense? Most of the [Scryer Prolog contributors](https://github.com/mthom/scryer-prolog/graphs/contributors) (which could address the issues) [don't watch this repo](https://github.com/aarroyoc/scryer-playground/watchers).

**Comment by Jean-Luc-Picard-2021** [comment]
I made many contributions to the original Scryer Prolog
issues list. But then UNW or some other guy blocked me,
now I am not able to post issues anymore. 

I am only able to post issues here. If I would get unblocked,
I would post in the original repo. But I am already used to
this phaenomenon, that there exist people on this

planet who cannot deal with criticism.

**Comment by Jean-Luc-Picard-2021** [comment]
@bakaq Easy explanation, as long as this banner shows for me:

![image](https://github.com/user-attachments/assets/4b564747-9831-4a8c-929b-24fd42d6aed4)

You have to watch here, as you already did.

**Comment by Jean-Luc-Picard-2021** [comment]
Closed because Ozzy Osbourne birthday and nobody is working on this bug.
